### ISSUE TITLE
Documentation: point to resource listing available instructions

### ISSUE THREAD

**Issue by scmbradley** [exercism/mips#222]
The instruction resources pointed to [here](https://exercism.org/docs/tracks/mips/resources) do not include some of the apparently valid instructions. In particular, neither of the reference cards -- [one](https://inst.eecs.berkeley.edu/~cs61c/resources/MIPS_Green_Sheet.pdf), [two](http://www.cburch.com/cs/330/reading/mips-ref.pdf) -- list the instructions `rem`, `bnez` or `beqz` which appear to work in the online editor. I think it would be good to point people to resources that list the available instructions.

**Comment by keiravillekode** [comment]
`rem`, `bnez` and `beqz` are pseudo-instructions that the assembler replaces with instructions.

`bnez $reg, label` is `bne $reg, $zero, label`

`beqz $reg, label` is `beq $reg, $zero, label`

`rem $dest, $s, $t` is `div $s, $t` followed by `mfhi $dest`

We can add the resource [MIPS Instruction Set Cheat Sheet](https://group.miletic.net/en/teaching/materials/mips-instruction-set/). It documents these particular pseudo-instructions.

**Comment by keiravillekode** [comment]
We use the [MARS simulator](https://courses.missouristate.edu/kenvollmar/mars/help/marshelpintro.html)

> As of Release 4.0, MARS assembles and simulates 155 basic instructions of the MIPS-32 instruction set, approximately 370 pseudo-instructions or instruction variations, ...
> 
> Our guiding reference in implementing the instruction set has been Computer Organization and Design, Fourth Edition by Patterson and Hennessy, Elsevier - Morgan Kaufmann, 2009. It summarizes the MIPS-32 instruction set and pseudo-instructions in Figures 3.24 and 3.25 on pages 279-281, with details provided in the text and in Appendix B. MARS Releases 3.2 and above implement all the instructions in Appendix B and those figures except the delay branches from the left column of Figure 3.25. It also implements all the system services (syscalls) and assembler directives documented in Appendix B.
> 

`Computer Organization and Design` is mentioned on [How to learn MIPS Assembly](https://exercism.org/docs/tracks/mips/learning) and I don't think we need to mention it again on [Useful MIPS Assembly resources](https://exercism.org/docs/tracks/mips/resources)

We should add a link to [Writing and Using Macros](https://courses.missouristate.edu/kenvollmar/mars/help/MacrosHelp.html)

**Comment by keiravillekode** [comment]
There remain instructions that none of these resources (other than `Computer Organization and Design`) document. For example, [MIPS-I Assembly Language Instruction Set](https://user.eng.umd.edu/~manoj/759M/MIPSALM.html) mentions `bltzal` but omits many pseudo-instructions. 

For a comprehensive listing, I think pointing people to `Computer Organization and Design` is the best we can do.
